
package com.ipcommerce.schemas.cws.v2_0.dataservices.billing;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-25T13:53:38.122-06:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "BillingTransactionFailedFault", targetNamespace = "http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing")
public class IDataServicesBillingQueryBillingEventSummaryBillingTransactionFailedFaultFaultFaultMessage extends Exception {
    
    private com.ipcommerce.schemas.cws.v2_0.dataservices.billing.BillingTransactionFailedFault billingTransactionFailedFault;

    public IDataServicesBillingQueryBillingEventSummaryBillingTransactionFailedFaultFaultFaultMessage() {
        super();
    }
    
    public IDataServicesBillingQueryBillingEventSummaryBillingTransactionFailedFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public IDataServicesBillingQueryBillingEventSummaryBillingTransactionFailedFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IDataServicesBillingQueryBillingEventSummaryBillingTransactionFailedFaultFaultFaultMessage(String message, com.ipcommerce.schemas.cws.v2_0.dataservices.billing.BillingTransactionFailedFault billingTransactionFailedFault) {
        super(message);
        this.billingTransactionFailedFault = billingTransactionFailedFault;
    }

    public IDataServicesBillingQueryBillingEventSummaryBillingTransactionFailedFaultFaultFaultMessage(String message, com.ipcommerce.schemas.cws.v2_0.dataservices.billing.BillingTransactionFailedFault billingTransactionFailedFault, Throwable cause) {
        super(message, cause);
        this.billingTransactionFailedFault = billingTransactionFailedFault;
    }

    public com.ipcommerce.schemas.cws.v2_0.dataservices.billing.BillingTransactionFailedFault getFaultInfo() {
        return this.billingTransactionFailedFault;
    }
}
