
package com.ipcommerce.schemas.cws.v2_0.serviceinformation;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-25T15:02:10.461-06:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "NonRenewableTokenFault", targetNamespace = "http://schemas.ipcommerce.com/Identity/1.0/")
public class ICWSServiceInformationRenewNonRenewableTokenFaultFaultFaultMessage extends Exception {
    
    private com.ipcommerce.schemas.identity._1.NonRenewableTokenFault nonRenewableTokenFault;

    public ICWSServiceInformationRenewNonRenewableTokenFaultFaultFaultMessage() {
        super();
    }
    
    public ICWSServiceInformationRenewNonRenewableTokenFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ICWSServiceInformationRenewNonRenewableTokenFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ICWSServiceInformationRenewNonRenewableTokenFaultFaultFaultMessage(String message, com.ipcommerce.schemas.identity._1.NonRenewableTokenFault nonRenewableTokenFault) {
        super(message);
        this.nonRenewableTokenFault = nonRenewableTokenFault;
    }

    public ICWSServiceInformationRenewNonRenewableTokenFaultFaultFaultMessage(String message, com.ipcommerce.schemas.identity._1.NonRenewableTokenFault nonRenewableTokenFault, Throwable cause) {
        super(message, cause);
        this.nonRenewableTokenFault = nonRenewableTokenFault;
    }

    public com.ipcommerce.schemas.identity._1.NonRenewableTokenFault getFaultInfo() {
        return this.nonRenewableTokenFault;
    }
}
