
package com.ipcommerce.schemas.cws.v2_0.serviceinformation;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-25T15:02:10.180-06:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "PasswordInvalidFault", targetNamespace = "http://schemas.ipcommerce.com/Identity/1.0/")
public class ICWSServiceInformationChangePasswordForServiceKeyPasswordInvalidFaultFaultFaultMessage extends Exception {
    
    private com.ipcommerce.schemas.identity._1.PasswordInvalidFault passwordInvalidFault;

    public ICWSServiceInformationChangePasswordForServiceKeyPasswordInvalidFaultFaultFaultMessage() {
        super();
    }
    
    public ICWSServiceInformationChangePasswordForServiceKeyPasswordInvalidFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ICWSServiceInformationChangePasswordForServiceKeyPasswordInvalidFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ICWSServiceInformationChangePasswordForServiceKeyPasswordInvalidFaultFaultFaultMessage(String message, com.ipcommerce.schemas.identity._1.PasswordInvalidFault passwordInvalidFault) {
        super(message);
        this.passwordInvalidFault = passwordInvalidFault;
    }

    public ICWSServiceInformationChangePasswordForServiceKeyPasswordInvalidFaultFaultFaultMessage(String message, com.ipcommerce.schemas.identity._1.PasswordInvalidFault passwordInvalidFault, Throwable cause) {
        super(message, cause);
        this.passwordInvalidFault = passwordInvalidFault;
    }

    public com.ipcommerce.schemas.identity._1.PasswordInvalidFault getFaultInfo() {
        return this.passwordInvalidFault;
    }
}
