
package com.ipcommerce.schemas.cws.v2_0.serviceinformation;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-25T15:02:10.354-06:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "LockedByAdminFault", targetNamespace = "http://schemas.ipcommerce.com/Identity/1.0/")
public class ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyLockedByAdminFaultFaultFaultMessage extends Exception {
    
    private com.ipcommerce.schemas.identity._1.LockedByAdminFault lockedByAdminFault;

    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyLockedByAdminFaultFaultFaultMessage() {
        super();
    }
    
    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyLockedByAdminFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyLockedByAdminFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyLockedByAdminFaultFaultFaultMessage(String message, com.ipcommerce.schemas.identity._1.LockedByAdminFault lockedByAdminFault) {
        super(message);
        this.lockedByAdminFault = lockedByAdminFault;
    }

    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyLockedByAdminFaultFaultFaultMessage(String message, com.ipcommerce.schemas.identity._1.LockedByAdminFault lockedByAdminFault, Throwable cause) {
        super(message, cause);
        this.lockedByAdminFault = lockedByAdminFault;
    }

    public com.ipcommerce.schemas.identity._1.LockedByAdminFault getFaultInfo() {
        return this.lockedByAdminFault;
    }
}
