
package com.ipcommerce.schemas.cws.v2_0.serviceinformation;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-25T15:02:09.776-06:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "CWSFault", targetNamespace = "http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")
public class ICWSServiceInformationGetServiceInformationCWSFaultFaultFaultMessage extends Exception {
    
    private com.ipcommerce.schemas.cws.v2_0.serviceinformation.faults.CWSFault cwsFault;

    public ICWSServiceInformationGetServiceInformationCWSFaultFaultFaultMessage() {
        super();
    }
    
    public ICWSServiceInformationGetServiceInformationCWSFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ICWSServiceInformationGetServiceInformationCWSFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ICWSServiceInformationGetServiceInformationCWSFaultFaultFaultMessage(String message, com.ipcommerce.schemas.cws.v2_0.serviceinformation.faults.CWSFault cwsFault) {
        super(message);
        this.cwsFault = cwsFault;
    }

    public ICWSServiceInformationGetServiceInformationCWSFaultFaultFaultMessage(String message, com.ipcommerce.schemas.cws.v2_0.serviceinformation.faults.CWSFault cwsFault, Throwable cause) {
        super(message, cause);
        this.cwsFault = cwsFault;
    }

    public com.ipcommerce.schemas.cws.v2_0.serviceinformation.faults.CWSFault getFaultInfo() {
        return this.cwsFault;
    }
}
