
package com.ipcommerce.schemas.cws.v2_0.serviceinformation;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-25T15:02:10.337-06:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "PasswordExpiredFault", targetNamespace = "http://schemas.ipcommerce.com/Identity/1.0/")
public class ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyPasswordExpiredFaultFaultFaultMessage extends Exception {
    
    private com.ipcommerce.schemas.identity._1.PasswordExpiredFault passwordExpiredFault;

    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyPasswordExpiredFaultFaultFaultMessage() {
        super();
    }
    
    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyPasswordExpiredFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyPasswordExpiredFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyPasswordExpiredFaultFaultFaultMessage(String message, com.ipcommerce.schemas.identity._1.PasswordExpiredFault passwordExpiredFault) {
        super(message);
        this.passwordExpiredFault = passwordExpiredFault;
    }

    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyPasswordExpiredFaultFaultFaultMessage(String message, com.ipcommerce.schemas.identity._1.PasswordExpiredFault passwordExpiredFault, Throwable cause) {
        super(message, cause);
        this.passwordExpiredFault = passwordExpiredFault;
    }

    public com.ipcommerce.schemas.identity._1.PasswordExpiredFault getFaultInfo() {
        return this.passwordExpiredFault;
    }
}
