
package com.ipcommerce.schemas.cws.v2_0.serviceinformation;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-25T15:02:09.995-06:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "RelyingPartyNotAssociatedToSecurityDomainFault", targetNamespace = "http://schemas.ipcommerce.com/Identity/1.0/")
public class ICWSServiceInformationGetClaimsRelyingPartyNotAssociatedToSecurityDomainFaultFaultFaultMessage extends Exception {
    
    private com.ipcommerce.schemas.identity._1.RelyingPartyNotAssociatedToSecurityDomainFault relyingPartyNotAssociatedToSecurityDomainFault;

    public ICWSServiceInformationGetClaimsRelyingPartyNotAssociatedToSecurityDomainFaultFaultFaultMessage() {
        super();
    }
    
    public ICWSServiceInformationGetClaimsRelyingPartyNotAssociatedToSecurityDomainFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ICWSServiceInformationGetClaimsRelyingPartyNotAssociatedToSecurityDomainFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ICWSServiceInformationGetClaimsRelyingPartyNotAssociatedToSecurityDomainFaultFaultFaultMessage(String message, com.ipcommerce.schemas.identity._1.RelyingPartyNotAssociatedToSecurityDomainFault relyingPartyNotAssociatedToSecurityDomainFault) {
        super(message);
        this.relyingPartyNotAssociatedToSecurityDomainFault = relyingPartyNotAssociatedToSecurityDomainFault;
    }

    public ICWSServiceInformationGetClaimsRelyingPartyNotAssociatedToSecurityDomainFaultFaultFaultMessage(String message, com.ipcommerce.schemas.identity._1.RelyingPartyNotAssociatedToSecurityDomainFault relyingPartyNotAssociatedToSecurityDomainFault, Throwable cause) {
        super(message, cause);
        this.relyingPartyNotAssociatedToSecurityDomainFault = relyingPartyNotAssociatedToSecurityDomainFault;
    }

    public com.ipcommerce.schemas.identity._1.RelyingPartyNotAssociatedToSecurityDomainFault getFaultInfo() {
        return this.relyingPartyNotAssociatedToSecurityDomainFault;
    }
}
