
package com.ipcommerce.schemas.cws.v2_0.dataservices.tms;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-25T15:04:42.918-06:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "TMSOperationNotSupportedFault", targetNamespace = "http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")
public class ITMSOperationsQueryRejectedDetailTMSOperationNotSupportedFaultFaultFaultMessage extends Exception {
    
    private com.ipcommerce.schemas.cws.v2_0.dataservices.tms.faults.TMSOperationNotSupportedFault tmsOperationNotSupportedFault;

    public ITMSOperationsQueryRejectedDetailTMSOperationNotSupportedFaultFaultFaultMessage() {
        super();
    }
    
    public ITMSOperationsQueryRejectedDetailTMSOperationNotSupportedFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ITMSOperationsQueryRejectedDetailTMSOperationNotSupportedFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ITMSOperationsQueryRejectedDetailTMSOperationNotSupportedFaultFaultFaultMessage(String message, com.ipcommerce.schemas.cws.v2_0.dataservices.tms.faults.TMSOperationNotSupportedFault tmsOperationNotSupportedFault) {
        super(message);
        this.tmsOperationNotSupportedFault = tmsOperationNotSupportedFault;
    }

    public ITMSOperationsQueryRejectedDetailTMSOperationNotSupportedFaultFaultFaultMessage(String message, com.ipcommerce.schemas.cws.v2_0.dataservices.tms.faults.TMSOperationNotSupportedFault tmsOperationNotSupportedFault, Throwable cause) {
        super(message, cause);
        this.tmsOperationNotSupportedFault = tmsOperationNotSupportedFault;
    }

    public com.ipcommerce.schemas.cws.v2_0.dataservices.tms.faults.TMSOperationNotSupportedFault getFaultInfo() {
        return this.tmsOperationNotSupportedFault;
    }
}
