
package com.ipcommerce.schemas.cws.v2_0.dataservices.tms;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-25T15:04:42.847-06:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "DataServicesUnavailableFault", targetNamespace = "http://schemas.ipcommerce.com/CWS/v2.0/DataServices")
public class ITMSOperationsQueryBatchDataServicesUnavailableFaultFaultFaultMessage extends Exception {
    
    private com.ipcommerce.schemas.cws.v2_0.dataservices.DataServicesUnavailableFault dataServicesUnavailableFault;

    public ITMSOperationsQueryBatchDataServicesUnavailableFaultFaultFaultMessage() {
        super();
    }
    
    public ITMSOperationsQueryBatchDataServicesUnavailableFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ITMSOperationsQueryBatchDataServicesUnavailableFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ITMSOperationsQueryBatchDataServicesUnavailableFaultFaultFaultMessage(String message, com.ipcommerce.schemas.cws.v2_0.dataservices.DataServicesUnavailableFault dataServicesUnavailableFault) {
        super(message);
        this.dataServicesUnavailableFault = dataServicesUnavailableFault;
    }

    public ITMSOperationsQueryBatchDataServicesUnavailableFaultFaultFaultMessage(String message, com.ipcommerce.schemas.cws.v2_0.dataservices.DataServicesUnavailableFault dataServicesUnavailableFault, Throwable cause) {
        super(message, cause);
        this.dataServicesUnavailableFault = dataServicesUnavailableFault;
    }

    public com.ipcommerce.schemas.cws.v2_0.dataservices.DataServicesUnavailableFault getFaultInfo() {
        return this.dataServicesUnavailableFault;
    }
}
