
package com.ipcommerce.schemas.cws.v2_0.dataservices.tms;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-10-25T15:04:42.633-06:00
 * Generated source version: 2.7.0
 */

@WebFault(name = "TMSTransactionFailedFault", targetNamespace = "http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")
public class ITMSOperationsQueryRejectedSummaryTMSTransactionFailedFaultFaultFaultMessage extends Exception {
    
    private com.ipcommerce.schemas.cws.v2_0.dataservices.tms.faults.TMSTransactionFailedFault tmsTransactionFailedFault;

    public ITMSOperationsQueryRejectedSummaryTMSTransactionFailedFaultFaultFaultMessage() {
        super();
    }
    
    public ITMSOperationsQueryRejectedSummaryTMSTransactionFailedFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ITMSOperationsQueryRejectedSummaryTMSTransactionFailedFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ITMSOperationsQueryRejectedSummaryTMSTransactionFailedFaultFaultFaultMessage(String message, com.ipcommerce.schemas.cws.v2_0.dataservices.tms.faults.TMSTransactionFailedFault tmsTransactionFailedFault) {
        super(message);
        this.tmsTransactionFailedFault = tmsTransactionFailedFault;
    }

    public ITMSOperationsQueryRejectedSummaryTMSTransactionFailedFaultFaultFaultMessage(String message, com.ipcommerce.schemas.cws.v2_0.dataservices.tms.faults.TMSTransactionFailedFault tmsTransactionFailedFault, Throwable cause) {
        super(message, cause);
        this.tmsTransactionFailedFault = tmsTransactionFailedFault;
    }

    public com.ipcommerce.schemas.cws.v2_0.dataservices.tms.faults.TMSTransactionFailedFault getFaultInfo() {
        return this.tmsTransactionFailedFault;
    }
}
